version: "3.4"

volumes:
  rockets:

services:
  rockets-playground-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rockets-playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
